### PR TITLE
fix typos in Source ids in changeset

### PR DESCRIPTION
**Pull request by regan-sarwas**

### CODE REVIEW

**Comment by jimmyrocks** [comment]
Thanks! I didn't test it, I just went through and tried to make it a little
more uniform to the code I was writing before. Sorry I broke it!

**Comment by jimmyrocks** [comment]
Merged and redeployed in dev, test, and prod

**Comment by regan-sarwas** [comment]
hmm...  I am getting a 404 for http://10.147.153.193:8000/api/data/source/3322.
I can see the changeset at http://10.147.153.193:8000/api/0.6/changeset/3322 and when I execute the query on test_places_api via psql, I get the expected results.  Anything helpful in the debug output?

**Comment by regan-sarwas** [comment]
Its working now! Thanks!!!

**Comment by jimmyrocks** [comment]
Sorry about that, Nate is working on the test environment as well. I think
it may have lagged behind dev and prod for the last hour.

**Pull request merged**
